export const dashboardData = [
  {
    timestamp: "1",
    tvl: 1,
    treasuryDaiMarketValue: 1,
    treasuryFraxMarketValue: 2,
    runwayCurrent: 1,
  },
  {
    timestamp: "2",
    tvl: 2,
    treasuryDaiMarketValue: 2,
    treasuryFraxMarketValue: 3,
    runwayCurrent: 2,
  },
  {
    timestamp: "3",
    tvl: 3,
    treasuryDaiMarketValue: 3,
    treasuryFraxMarketValue: 4,
    runwayCurrent: 2.5,
  },
  {
    timestamp: "4",
    tvl: 4,
    treasuryDaiMarketValue: 1,
    treasuryFraxMarketValue: 2,
    runwayCurrent: 3,
  },
  {
    timestamp: "5",
    tvl: 5,
    treasuryDaiMarketValue: 1,
    treasuryFraxMarketValue: 5,
    runwayCurrent: 4,
  },
  {
    timestamp: "6",
    tvl: 6,
    treasuryDaiMarketValue: 3,
    treasuryFraxMarketValue: 6,
    runwayCurrent: 4.3,
  },
  {
    timestamp: "7",
    tvl: 7,
    treasuryDaiMarketValue: 1,
    treasuryFraxMarketValue: 2,
    runwayCurrent: 5,
  },
  {
    timestamp: "8",
    tvl: 8,
    treasuryDaiMarketValue: 5,
    treasuryFraxMarketValue: 2,
    runwayCurrent: 6,
  },
  {
    timestamp: "9",
    tvl: 9,
    treasuryDaiMarketValue: 3,
    treasuryFraxMarketValue: 4,
    runwayCurrent: 7,
  },
  {
    timestamp: "10",
    tvl: 10,
    treasuryDaiMarketValue: 1,
    treasuryFraxMarketValue: 2,
    runwayCurrent: 7.1,
  },
];
